[package]
name = "howmanysmall/fast-fzy"
description = "A faster implementation of Fzy."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.0"
exclude = [
	".moonwave",
	"build",
	"docs",
	"Packages",
	"test",

	".gitignore",
	"aftman.toml",
	"changelog.md",
	"moonwave.toml",
	"README.md",
	"selene.toml",
	"sourcemap.json",
	"stylua.toml",
	"testez-companion.toml",
	"testez.yml",
]

[dependencies]
